### ISSUE TITLE
Handle comment delimiters not on same line as 'todo' keyword

### ISSUE THREAD

**Issue by klein0r** [alstr/todo-to-issue-action#119]
Comments are defined like this:

```
..
    _This: is a comment!

..
    [and] this!

..
    this:: too!

..
    |even| this:: !
```

Additionally, support for https://www.sphinx-doc.org/en/master/usage/extensions/todo.html would be awesome

```
.. todo::
     This is a todo
```

**Comment by alstr** [comment]
Interesting, thanks for the suggestion! It would definitely be good to add this; PR requests are always welcome for new languages, and they're relatively easy to do. This does look a little more complicated than the standard comment syntax. For one, at the moment if the comment delimiter is not on the same line as the 'todo' keyword/title, it won't get picked up, but that is something I am hoping to improve.

**Comment by alstr** [comment]
I've done some experimentation and the challenges to adding this at the moment are:

- [x] The lowercase `todo` (added support in latest commit)
- [ ] The double colon after `todo` (at the moment it thinks the second colon is the title)
- [ ] The fact that the formatting is somewhat unique; it isn't like a normal line comment as there is no comment delimiter on the second line, but it isn't a block comment as there's no closing tag.

The second one is an easy fix; the third is a bit more involved.

**Comment by silopolis** [comment]
We'd surely be a bunch to welcome this addition!
Thanks for taking care of it :)

**Comment by alstr** [comment]
The next version should support this style:

`.. todo:: This is my issue title.`

However, the below presents challenges I can't accommodate yet:

```
.. todo::

   This is another issue title and it
   breaks across multiple lines.
```

Mainly because the action doesn't associate those two lines as comments. This is something fundamental to how the action works, so no easy workaround currently.
